-- ============================================================================
-- Clones de teste para o gate de escrita da Fase 5 (migração web).
-- Rodar uma vez com a mesma role usada pelo painel (local_cli). A role
-- GENERAL_ANALYST não tem CREATE SCHEMA em SUPERSET, então os clones ficam
-- como TABELAS prefixadas MIGTESTE_ dentro do schema COMISSOES (permitido),
-- em vez de um schema clonado inteiro.
--
-- Uso: webapp/services/admin_repo.py redireciona leitura e escrita para
-- estas tabelas quando WRITES_TARGET=clone (env var). Em produção
-- (WRITES_TARGET=prod, o default) tabela_escrita() é identidade — nada
-- disto é tocado.
--
-- Refrescar os clones (dados ficam defasados com o tempo — recriar quando
-- precisar validar contra dados mais recentes):
--   CREATE OR REPLACE TABLE SUPERSET.COMISSOES.MIGTESTE_X CLONE SUPERSET.COMISSOES.X;
-- ============================================================================

CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_CARGOS_OTES
  CLONE SUPERSET.COMISSOES.CARGOS_OTES;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_ACEL_FORMA_PAGAMENTO
  CLONE SUPERSET.COMISSOES.ACEL_FORMA_PAGAMENTO;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_PATAMARES_COMISSAO
  CLONE SUPERSET.COMISSOES.PATAMARES_COMISSAO;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_RECUPERACAO_DIVIDAS
  CLONE SUPERSET.COMISSOES.RECUPERACAO_DIVIDAS;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_DEALS_PAGOS_400K
  CLONE SUPERSET.COMISSOES.DEALS_PAGOS_400K;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_REALIZADO_GD_OVERRIDE
  CLONE SUPERSET.COMISSOES.REALIZADO_GD_OVERRIDE;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_PONDERACOES_META
  CLONE SUPERSET.COMISSOES.PONDERACOES_META;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_AJUSTES_PONTUAIS
  CLONE SUPERSET.COMISSOES.AJUSTES_PONTUAIS;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_EXCLUSOES_CARTEIRA_AM
  CLONE SUPERSET.COMISSOES.EXCLUSOES_CARTEIRA_AM;
-- PERMISSAO_RLS mora em SUPERSET.PARCIAL; o clone fica junto dos demais em
-- COMISSOES (mesmo motivo: sem CREATE SCHEMA em PARCIAL nem em COMISSOES).
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_PERMISSAO_RLS
  CLONE SUPERSET.PARCIAL.PERMISSAO_RLS;

-- Grades editáveis (Parâmetros, Metas) e Config com vigência, adicionadas
-- depois da Fase 5 (18/08/2026) quando essas 3 telas deixaram de ser
-- somente leitura. META_CONSULTOR também mora em SUPERSET.PARCIAL.
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_PARAMETROS
  CLONE SUPERSET.COMISSOES.PARAMETROS;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_META_CONSULTOR
  CLONE SUPERSET.PARCIAL.META_CONSULTOR;
CREATE TABLE IF NOT EXISTS SUPERSET.COMISSOES.MIGTESTE_CONFIG
  CLONE SUPERSET.COMISSOES.CONFIG;
