-- ============================================================================
-- Painel de Comissões (webapp) — service account + role
-- Enviar ao admin do Snowflake (precisa de SECURITYADMIN/ACCOUNTADMIN).
-- Contexto: o painel está migrando de Streamlit-in-Snowflake para um app web
-- próprio (FastAPI). O app conecta com usuário de SERVIÇO via key-pair.
-- Plano: docs/21_migracao_web.md (Fase 0).
--
-- Antes de rodar: gerar o par de chaves na máquina segura do time e colar a
-- chave PÚBLICA no ALTER USER abaixo (sem cabeçalho/rodapé PEM):
--   openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out sf_key.p8 -nocrypt
--   openssl rsa -in sf_key.p8 -pubout -out sf_key.pub
-- ============================================================================

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_PAINEL_COMISSOES_APP
  COMMENT = 'App web do Painel de Comissões (leitura de vendas/contratos/metas e escrita nas tabelas de comissões)';

CREATE USER IF NOT EXISTS SVC_PAINEL_COMISSOES
  TYPE = SERVICE
  DEFAULT_ROLE = ROLE_PAINEL_COMISSOES_APP
  DEFAULT_WAREHOUSE = DATAANALYST_WH
  COMMENT = 'Service account do app web Painel de Comissões';

-- Colar a chave pública (conteúdo de sf_key.pub sem BEGIN/END):
-- ALTER USER SVC_PAINEL_COMISSOES SET RSA_PUBLIC_KEY = 'MIIBIjANBg...';

GRANT ROLE ROLE_PAINEL_COMISSOES_APP TO USER SVC_PAINEL_COMISSOES;

-- ── Warehouse ───────────────────────────────────────────────────────────────
GRANT USAGE ON WAREHOUSE DATAANALYST_WH TO ROLE ROLE_PAINEL_COMISSOES_APP;

-- ── Leitura (o cálculo lê estes 5 schemas) ─────────────────────────────────
GRANT USAGE ON DATABASE HUBSPOT TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT USAGE ON SCHEMA HUBSPOT.HUBSPOT_OURO TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT USAGE ON SCHEMA HUBSPOT.HUBSPOT_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA HUBSPOT.HUBSPOT_OURO TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HUBSPOT.HUBSPOT_OURO TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA HUBSPOT.HUBSPOT_OURO TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HUBSPOT.HUBSPOT_OURO TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA HUBSPOT.HUBSPOT_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HUBSPOT.HUBSPOT_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA HUBSPOT.HUBSPOT_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA HUBSPOT.HUBSPOT_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;

GRANT USAGE ON DATABASE REVENUE_INTELLIGENCE TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT USAGE ON SCHEMA REVENUE_INTELLIGENCE.REVENUE_INTELLIGENCE_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA REVENUE_INTELLIGENCE.REVENUE_INTELLIGENCE_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REVENUE_INTELLIGENCE.REVENUE_INTELLIGENCE_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA REVENUE_INTELLIGENCE.REVENUE_INTELLIGENCE_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA REVENUE_INTELLIGENCE.REVENUE_INTELLIGENCE_PRATA TO ROLE ROLE_PAINEL_COMISSOES_APP;

-- ── Leitura + escrita (tabelas administradas pelo painel) ──────────────────
GRANT USAGE ON DATABASE SUPERSET TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT USAGE ON SCHEMA SUPERSET.COMISSOES TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT USAGE ON SCHEMA SUPERSET.PARCIAL TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SUPERSET.COMISSOES TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SUPERSET.COMISSOES TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPERSET.COMISSOES TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPERSET.COMISSOES TO ROLE ROLE_PAINEL_COMISSOES_APP;
-- PARCIAL: o app lê a view consolidada e escreve em META_CONSULTOR e PERMISSAO_RLS
GRANT SELECT ON ALL TABLES IN SCHEMA SUPERSET.PARCIAL TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPERSET.PARCIAL TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPERSET.PARCIAL TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPERSET.PARCIAL TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT INSERT, UPDATE, DELETE ON TABLE SUPERSET.PARCIAL.META_CONSULTOR TO ROLE ROLE_PAINEL_COMISSOES_APP;
GRANT INSERT, UPDATE, DELETE ON TABLE SUPERSET.PARCIAL.PERMISSAO_RLS TO ROLE ROLE_PAINEL_COMISSOES_APP;

-- NÃO conceder: SNOWFLAKE.ACCOUNT_USAGE (a identidade do usuário passa a vir
-- do login Google do app, não mais do Snowflake).
